version: '3.8'
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=$DATABASE_URL
    restart: "no"

  inventory_management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=$DATABASE_URL
    restart: "no"
