name: Deploy microservices

on:
  # Trigger the workflow on pushes to the main branch
  push: 
    branches:
      - main
    paths:
      - book_catalog/**
      - inventory_management/**
  
  # Allow manual trigger through GitHub Actions UI
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make the scripts executable
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/build-image.sh
          chmod +x ./scripts/push-image.sh
          chmod +x ./scripts/deploy.sh

      # -------------------------
      # Deploy book-catalog
      # -------------------------

      # Build book-catalog
      - name: Build book-catalog
        env:
          NAME: book-catalog
          DIRECTORY: book_catalog
        run: ./scripts/build-image.sh

      # Publish book-catalog
      - name: Publish book-catalog
        env:
          NAME: book-catalog
          DIRECTORY: book_catalog
        run: ./scripts/push-image.sh

      # Install Kubectl for book-catalog
      - name: Install Kubectl for book-catalog
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
      
      # Deploy book-catalog to Kubernetes
      - name: Deploy book-catalog
        env:
          NAME: book-catalog
          DIRECTORY: book_catalog
        run: ./scripts/deploy.sh

      # -------------------------
      # Deploy inventory-management
      # -------------------------

      # Build inventory-management
      - name: Build inventory-management
        env:
          NAME: inventory-management
          DIRECTORY: inventory_management
        run: ./scripts/build-image.sh

      # Publish inventory-management
      - name: Publish inventory-management
        env:
          NAME: inventory-management
          DIRECTORY: inventory_management
        run: ./scripts/push-image.sh

      # Install Kubectl for inventory-management
      - name: Install Kubectl for inventory-management
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
          
      # Deploy
